/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.Admin;

import api.RegistroAccidenteDetalleService;
import api.RegistroAccidenteService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.table.DefaultTableModel;
import models.RegistroAccidenteDetalle;
import models.Usuario;
import org.json.JSONArray;
import org.json.JSONObject;
import principal.Principal;
import static principal.Admin.DashboardAdmin.lblNombreUsuario;

/**
 *
 * @author AlexF
 */
public class MantenedorRegistroAccidenteDetalle extends javax.swing.JFrame {

    String registroAccidenteId;
     int posicion = 100;
    /**
     * Creates new form MantenedorRegistroAccidenteDetalle
     */
    public MantenedorRegistroAccidenteDetalle() {
        initComponents();
    }

    public MantenedorRegistroAccidenteDetalle(String registroDetalleId) {
        initComponents();
     
        
        
        RegistroAccidenteDetalleService accidenteDetalleService = new RegistroAccidenteDetalleService();
        
        
        registroAccidenteId = (registroDetalleId);
        String array =  accidenteDetalleService.getRegistrosAccidentesDetalleByRegistro(Integer.parseInt(registroAccidenteId));
       
        JSONObject obj = new JSONObject(array);        
        JSONArray data = obj.getJSONArray("data");   

        
        JtableMensajes.setModel(this.showData());
        
//        if(data.length() != 0){
//            
//            
//            System.out.println(data.length());
//            
//            for (int i = 0; i < data.length(); i++) {
//                 JSONObject row = data.getJSONObject(i);
//                JLabel labelNombreUsuario = new JLabel();    
//                
//                labelNombreUsuario.setVisible(true);
//                labelNombreUsuario.setText(row.getString("REGISTRO_ACCIDENTE_DET_USUARIO"));
//                labelNombreUsuario.setBounds(100, posicion, 600, 50);
//                
//                JLabel labelMensaje = new JLabel();
//                labelMensaje.setVisible(true);
//                labelMensaje.setText(row.getString("REGISTRO_ACCIDENTE_DET_NOMBRE"));
//                labelMensaje.setBounds(200, posicion, 600, 50);
//                JSeparator separator = new JSeparator();
//                separator.setVisible(true);
//                separator.setBounds(100, posicion+50, 600, 50);
//                panelAlmacenaMensajes.add(labelNombreUsuario);
//                panelAlmacenaMensajes.add(labelMensaje);
//                panelAlmacenaMensajes.add(separator);
//                panelAlmacenaMensajes.repaint();
//                panelAlmacenaMensajes.revalidate();
//                
//                posicion += 50;
//            }
            
            
            


//        }
        
        
        lblRegistroAccidenteId.setText(registroAccidenteId);
    }
    
    
      public DefaultTableModel showData(){
        RegistroAccidenteDetalleService registroAccidenteService = new RegistroAccidenteDetalleService();
        DefaultTableModel dtm = new DefaultTableModel();
        
        dtm.addColumn("Usuario");
        dtm.addColumn("Mensaje");
        dtm.addColumn("Fecha");
        
        String array = registroAccidenteService.getRegistrosAccidentesDetalleByRegistro(Integer.parseInt(registroAccidenteId));        
        JSONObject obj = new JSONObject(array);        
        Usuario u = new Usuario();
        JSONArray data = obj.getJSONArray("data");               
        for (int i = 0; i < data.length(); i++) {
                JSONObject row = data.getJSONObject(i);
                dtm.addRow(new Object[]{row.getString("REGISTRO_ACCIDENTE_DET_USUARIO"),row.getString("REGISTRO_ACCIDENTE_DET_NOMBRE"), row.getString("REGISTRO_ACCIDENTE_DET_FECHA")});
        }
        
        return dtm;
        
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRegistroAccidenteId = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensajeDetalle = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtableMensajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Accidente ID : ");

        jButton2.setText("Cerrar Ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(lblRegistroAccidenteId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblRegistroAccidenteId)
                    .addComponent(jButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        txaMensajeDetalle.setColumns(20);
        txaMensajeDetalle.setRows(5);
        jScrollPane1.setViewportView(txaMensajeDetalle);

        jButton1.setText("Agregar Mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JtableMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JtableMensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        RegistroAccidenteDetalle accidenteDetalle = new RegistroAccidenteDetalle();
        
        accidenteDetalle.registroAccidenteDetalleUsuario = lblNombreUsuario.getText();
        accidenteDetalle.registroAccidenteDetalleNombre = txaMensajeDetalle.getText();
        accidenteDetalle.registroAccidenteId = Integer.parseInt(lblRegistroAccidenteId.getText());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
	LocalDate localDate = LocalDate.now();
        
        accidenteDetalle.registroAccidenteDetalleFecha = dtf.format(localDate);
	
        
        RegistroAccidenteDetalleService accidenteDetalleService = new RegistroAccidenteDetalleService();
        
        try {
            accidenteDetalleService.postRegistroAccidenteDetalle(accidenteDetalle);
            JOptionPane.showMessageDialog(null, "Comentario Ingresado Correctamente");
            this.setVisible(false);
            MantenedorRegistroAccidenteDetalle accidenteDetalle1 = new MantenedorRegistroAccidenteDetalle(registroAccidenteId);
            accidenteDetalle1.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MantenedorRegistroAccidenteDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorRegistroAccidenteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorRegistroAccidenteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorRegistroAccidenteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorRegistroAccidenteDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorRegistroAccidenteDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableMensajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRegistroAccidenteId;
    private javax.swing.JTextArea txaMensajeDetalle;
    // End of variables declaration//GEN-END:variables
}
