/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.Admin;

import api.AsesoriaDetalleService;
import com.google.gson.JsonObject;
import java.awt.Button;
import java.awt.Component;
import java.awt.Container;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ScrollBar;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.tree.DefaultTreeCellEditor;
import models.AsesoriaDetalle;
import models.Usuario;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author AlexF
 */
public class MantenedorAsesoriaDetalle extends javax.swing.JFrame {

    
    int posicion = 100;
    
    int idElemento = 0;
    public JLabel label;
    int idAsesoria;
    int idContrato;
    private HashMap componentMap;
    /**
     * Creates new form MantenedorAsesoriaDetalle
     */
    public MantenedorAsesoriaDetalle() {
        initComponents();
        
    }

    public MantenedorAsesoriaDetalle(String id, String contratoId) {
        
        
        idContrato = Integer.parseInt(contratoId);
        idAsesoria = Integer.parseInt(id);
        
        AsesoriaDetalleService ads = new AsesoriaDetalleService();
        String array = ads.getAsesoriaDetalleById(idAsesoria);   
        JSONObject obj = new JSONObject(array);        
        Usuario u = new Usuario();
        JSONArray data = obj.getJSONArray("data");   
        
        
        System.out.println(data);
        initComponents();
        this.numAsesoria.setText(id);
        if(data.length() != 0){
            botonAgregaDetalle.setVisible(false);
            btnCierraDetalle.setVisible(false);
            for (int i = 0; i < data.length(); i++) {
                    JSONObject row = data.getJSONObject(i);
                    JTextField textField = new JTextField();
                    JCheckBox check = new JCheckBox();
                    textField.setVisible(true);
                    textField.setText(row.getString("ASESORIA_DETALLE_TITULO"));
                    textField.setBounds(10, posicion, 600, 50);
                    check.setVisible(true);
                    textField.setEditable(false);
                    if(row.getInt("ASESORIA_DETALLE_CHECK") == 1){
                        check.setSelected(true);
                    }else{
                        check.setSelected(false);
                    }
                    check.setBounds(640, posicion, 500, 50);
                    
                    panelAlmacenaDetalle.add(textField);
                    panelAlmacenaDetalle.add(check);
                    panelAlmacenaDetalle.repaint();
                    panelAlmacenaDetalle.revalidate();
                   
                    JScrollPane scroll = new JScrollPane(
                            new Panel(), 
                            ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS, 
                            ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS
                    );
                    panelAlmacenaDetalle.add(scroll);
                    idElemento +=1;
                    posicion += 50;
            }
        }else{
            this.botonAgregaDetalle.setVisible(true);
            this.btnCierraDetalle.setVisible(true);
        }
        
         
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlmacenaDetalle = new javax.swing.JPanel();
        botonAgregaDetalle = new javax.swing.JButton();
        btnCierraDetalle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numAsesoria = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelAlmacenaDetalleLayout = new javax.swing.GroupLayout(panelAlmacenaDetalle);
        panelAlmacenaDetalle.setLayout(panelAlmacenaDetalleLayout);
        panelAlmacenaDetalleLayout.setHorizontalGroup(
            panelAlmacenaDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        panelAlmacenaDetalleLayout.setVerticalGroup(
            panelAlmacenaDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        botonAgregaDetalle.setText("+");
        botonAgregaDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaDetalleActionPerformed(evt);
            }
        });

        btnCierraDetalle.setText("Agregar Detalle");
        btnCierraDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierraDetalleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Detalle Asesoria Id:");

        numAsesoria.setText("jLabel2");

        jButton1.setText("Cerrar ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reportar Accidente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(panelAlmacenaDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregaDetalle)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(numAsesoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnCierraDetalle)
                .addGap(245, 245, 245)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numAsesoria)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregaDetalle)
                    .addComponent(panelAlmacenaDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCierraDetalle)
                    .addComponent(jButton2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregaDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaDetalleActionPerformed
        // TODO add your handling code here:
        
        
        JTextField textField = new JTextField();
        JCheckBox check = new JCheckBox();
        textField.setVisible(true);
        textField.setName("tituloCheck"+idElemento);
        textField.setBounds(10, posicion, 600, 50);
        check.setVisible(true);
        check.setName("check"+idElemento);
        check.setBounds(620, posicion, 500, 50);
         JScrollPane scroll = new JScrollPane(
                            ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS, 
                            ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS
                    );
        panelAlmacenaDetalle.add(scroll);
        panelAlmacenaDetalle.add(textField);
        panelAlmacenaDetalle.add(check);
        panelAlmacenaDetalle.repaint();
        panelAlmacenaDetalle.revalidate();
        idElemento +=1;
        posicion += 50;
        
    }//GEN-LAST:event_botonAgregaDetalleActionPerformed

    private void btnCierraDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierraDetalleActionPerformed
        // TODO add your handling code here:
        
        
        System.out.println(this.idElemento);
       
        AsesoriaDetalleService ads = new AsesoriaDetalleService();
        
        int totalComponentes = panelAlmacenaDetalle.getComponentCount();
        
        String titulo = "";
        int isChecked = 0;
         int finaliado = 0;
       
//        System.out.println(arrListo.toString());
        
        
        
        for (int i = 0; i < panelAlmacenaDetalle.getComponentCount()/2; i++) {
            AsesoriaDetalle as = new AsesoriaDetalle();
            
            System.out.println();
          
            String nombre = (( JTextField) findComponentByName(panelAlmacenaDetalle, "tituloCheck"+i)).getText();
            
            as.asesoriaDetalleTitulo = nombre;
            
            if((( JCheckBox) findComponentByName(panelAlmacenaDetalle, "check"+i)).isSelected()){
                isChecked = 1;
            }else{
                isChecked = 0;
            }
            as.asesoriaDetalleCheck = isChecked;
           
            
             as.asesoriaId = idAsesoria;
        
            try {
               ads.postAsesoriaDetalle(as);
               finaliado = 1;
           } catch (Exception ex) {
               Logger.getLogger(MantenedorAsesoriaDetalle.class.getName()).log(Level.SEVERE, null, ex);
           }        
        }
        
        if(finaliado == 1){
            JOptionPane.showMessageDialog(null, "Detalle Asesoria INsertado");
        }
        
    }//GEN-LAST:event_btnCierraDetalleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        MantenedorInsertRegistroAcciente acciente = new MantenedorInsertRegistroAcciente(idAsesoria, idContrato);
        acciente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public Component findComponentByName(Container container, String componentName) {
        for (Component component: container.getComponents()) {
          if (componentName.equals(component.getName())) {
            return component;
          }
          if (component instanceof JRootPane) {
            // According to the JavaDoc for JRootPane, JRootPane is
            // "A lightweight container used behind the scenes by JFrame,
            // JDialog, JWindow, JApplet, and JInternalFrame.". The reference
            // to the RootPane is set up by implementing the RootPaneContainer
            // interface by the JFrame, JDialog, JWindow, JApplet and
            // JInternalFrame. See also the JavaDoc for RootPaneContainer.
            // When a JRootPane is found, recurse into it and continue searching.
            JRootPane nestedJRootPane = (JRootPane)component;
            return findComponentByName(nestedJRootPane.getContentPane(), componentName);
          }
          if (component instanceof JPanel) {
            // JPanel found. Recursing into this panel.
            JPanel nestedJPanel = (JPanel)component;
            return findComponentByName(nestedJPanel, componentName);
          }
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorAsesoriaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorAsesoriaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorAsesoriaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorAsesoriaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
               
                new MantenedorAsesoriaDetalle().setVisible(true);
                 System.out.println("llego primero");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregaDetalle;
    private javax.swing.JButton btnCierraDetalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numAsesoria;
    private javax.swing.JPanel panelAlmacenaDetalle;
    // End of variables declaration//GEN-END:variables
}
